import streamlit as st


def render_supervisor_result(result):
    st.caption(f"Estado: {result.status.value} · Routing: {result.routing.routing_method}")
    st.write("Seleccionados: " + (", ".join(result.routing.selected_agents) or "ninguno"))
    st.write("Omitidos: " + (", ".join(result.routing.skipped_agents) or "ninguno"))
    st.markdown(result.content)
    with st.expander("Resultado estructurado del Supervisor"):
        st.json(result.model_dump(mode="json"))
    st.download_button("Descargar resultado JSON", result.model_dump_json(indent=2),
                       "supervisor-result.json", "application/json", key="supervisor_json")


def supervisor_diagnostics(snapshot):
    events = snapshot.events
    routing = next((e.metadata for e in reversed(events) if e.stage == "routing"), {})
    lines = ["Supervisor Execution", "--------------------",
             f"Routing method: {routing.get('routing_method', 'pending')}",
             "Selected agents: " + ", ".join(routing.get("selected_agents", [])),
             "Skipped agents: " + ", ".join(routing.get("skipped_agents", [])),
             "Routing evidence: " + " ".join(routing.get("routing_reasons", []))]
    for event in events:
        if event.stage == "specialist_execution":
            data = event.metadata
            lines += ["", str(data.get("agent_name")), f"status: {data.get('status', event.status.value)}",
                      f"duration: {data.get('duration_seconds', event.duration_seconds or 0):.4f} s",
                      f"LLM calls: {data.get('llm_calls', 0)}", f"RAG calls: {data.get('rag_calls', 0)}",
                      f"tool calls: {data.get('tool_calls', 0)}", f"reused tool results: {data.get('reused_tool_results', 0)}"]
    result = next((e.metadata['structured_result'] for e in reversed(events) if e.stage == "supervisor_result"), {})
    for item in result.get("specialist_results", []):
        if item["agent_name"] == "CommercialAgent" and item.get("result"):
            lines.append("CommercialAgent interpretation mode: " + item["result"].get("interpretation_mode", "llm"))
    lines += ["", f"Supervisor synthesis: {result.get('synthesis_status', 'pending')}",
              f"Synthesis LLM calls: {result.get('synthesis_llm_calls', 0)}",
              f"Router LLM calls: {result.get('router_llm_calls', 0)}",
              f"Total wall time: {snapshot.elapsed_seconds:.4f} s (independent; includes nested agents)",
              f"Total LLM calls: {result.get('total_llm_calls', 0)}",
              f"Total RAG calls: {result.get('total_rag_calls', 0)}",
              f"Total tool calls: {result.get('total_tool_calls', 0)}"]
    return "\n".join(lines)


def render_supervisor_inspector(snapshot):
    st.text(supervisor_diagnostics(snapshot))
    for event in snapshot.events:
        owner = event.metadata.get("supervisor_agent", event.metadata.get("agent_name", "Supervisor"))
        with st.expander(f"{owner} · {event.stage} · {event.status.value}"):
            st.caption(f"Duración: {event.duration_seconds or 0:.4f} s")
            # Only validated public metadata is generated by Supervisor/adapters.
            from clipboard_text import _sanitize
            st.json(_sanitize(event.metadata))
